-- ============================================================================
-- Seed data: your existing categories/subcategories/products, migrated from the
-- previous static catalog. Run this AFTER schema.sql, in the Supabase SQL Editor.
-- ============================================================================

insert into categories (slug, name, name_ar, image, sort_order) values
  ('skincare', 'Skincare', 'العناية بالبشرة', 'https://res.cloudinary.com/djxxsn3dh/image/upload/f_auto,q_auto,w_1200/skincare_laya4u.png', 0),
  ('haircare', 'Hair Care', 'العناية بالشعر', 'https://res.cloudinary.com/djxxsn3dh/image/upload/f_auto,q_auto,w_1200/haircare_jpbbpg.png', 1),
  ('bodycare', 'Body Care', 'العناية بالجسم', 'https://res.cloudinary.com/djxxsn3dh/image/upload/f_auto,q_auto,w_1200/bodycare_vqtiqh.png', 2),
  ('kids', 'Kids', 'الأطفال', 'https://res.cloudinary.com/djxxsn3dh/image/upload/f_auto,q_auto,w_1200/kids_ffcbrz.png', 3),
  ('korean', 'Korean Beauty', 'جمال كوريا', 'https://res.cloudinary.com/djxxsn3dh/image/upload/f_auto,q_auto,w_1200/korean_gfoc4f.png', 4)
,
  ('makeup', 'Makeup', 'المكياج', 'https://picsum.photos/seed/cat-makeup/900/900', 5),
  ('fragrance', 'Fragrance', 'العطور', 'https://picsum.photos/seed/cat-fragrance/900/900', 6)
on conflict (slug) do nothing;

insert into subcategories (category_id, slug, name, sort_order) values
  ((select id from categories where slug = 'skincare'), 'cleansers', 'Cleansers', 0),
  ((select id from categories where slug = 'skincare'), 'moisturizers', 'Moisturizers', 1),
  ((select id from categories where slug = 'skincare'), 'sun-screens', 'Sun Screens', 2),
  ((select id from categories where slug = 'skincare'), 'serums', 'Serums', 3),
  ((select id from categories where slug = 'skincare'), 'eye-care', 'Eye Care', 4),
  ((select id from categories where slug = 'skincare'), 'micellar-water-and-tonic-lotions', 'Micellar Water & Tonic Lotions', 5),
  ((select id from categories where slug = 'skincare'), 'whitening-creams', 'Whitening Creams', 6),
  ((select id from categories where slug = 'skincare'), 'lip-balm', 'Lip Balm', 7),
  ((select id from categories where slug = 'skincare'), 'eye-lashes', 'Eye Lashes', 8),
  ((select id from categories where slug = 'skincare'), 'exfoliating', 'Exfoliating', 9),
  ((select id from categories where slug = 'haircare'), 'africana-npc', 'Africana NPC', 0),
  ((select id from categories where slug = 'haircare'), 'minoxidil', 'Minoxidil', 1),
  ((select id from categories where slug = 'haircare'), 'hair-dye', 'Hair Dye', 2),
  ((select id from categories where slug = 'haircare'), 'rush-brush', 'Rush Brush', 3),
  ((select id from categories where slug = 'haircare'), 'hair-dropper', 'Hair Dropper', 4),
  ((select id from categories where slug = 'haircare'), 'hair-oils', 'Hair Oils', 5),
  ((select id from categories where slug = 'haircare'), 'hair-vitamins', 'Hair Vitamins', 6),
  ((select id from categories where slug = 'haircare'), 'mist-and-heat-protector', 'Mist & Heat Protector', 7),
  ((select id from categories where slug = 'haircare'), 'hair-cream', 'Hair Cream', 8),
  ((select id from categories where slug = 'haircare'), 'hair-lotions', 'Hair Lotions', 9),
  ((select id from categories where slug = 'haircare'), 'shampoo', 'Shampoo', 10),
  ((select id from categories where slug = 'haircare'), 'hair-conditioner', 'Hair Conditioner', 11),
  ((select id from categories where slug = 'haircare'), 'mask-and-scrubs', 'Mask & Scrubs', 12),
  ((select id from categories where slug = 'haircare'), 'hair-serum', 'Hair Serum', 13),
  ((select id from categories where slug = 'haircare'), 'kids-products', 'Kids Products', 14),
  ((select id from categories where slug = 'bodycare'), 'body-scrub', 'Body Scrub', 0),
  ((select id from categories where slug = 'bodycare'), 'hand-care', 'Hand Care', 1),
  ((select id from categories where slug = 'bodycare'), 'oral-care', 'Oral Care', 2),
  ((select id from categories where slug = 'bodycare'), 'shower-gel', 'Shower Gel', 3),
  ((select id from categories where slug = 'bodycare'), 'body-spray', 'Body Spray', 4),
  ((select id from categories where slug = 'bodycare'), 'lotion', 'Lotion', 5),
  ((select id from categories where slug = 'bodycare'), 'nails-care', 'Nails Care', 6),
  ((select id from categories where slug = 'bodycare'), 'scrubs', 'Scrubs', 7),
  ((select id from categories where slug = 'bodycare'), 'whitening-wash-and-cream', 'Whitening Wash & Cream', 8),
  ((select id from categories where slug = 'bodycare'), 'roll-on', 'Roll ON', 9),
  ((select id from categories where slug = 'bodycare'), 'body-butter', 'Body Butter', 10),
  ((select id from categories where slug = 'kids'), 'lotion', 'Lotion', 0),
  ((select id from categories where slug = 'kids'), 'wash', 'Wash', 1),
  ((select id from categories where slug = 'korean'), 'essence', 'Essence', 0),
  ((select id from categories where slug = 'korean'), 'sheet-masks', 'Sheet Masks', 1)
,
  ((select id from categories where slug = 'makeup'), 'foundation', 'Foundation', 0),
  ((select id from categories where slug = 'makeup'), 'lips', 'Lips', 1),
  ((select id from categories where slug = 'makeup'), 'brows', 'Brows', 2),
  ((select id from categories where slug = 'fragrance'), 'eau-de-parfum', 'Eau de Parfum', 0),
  ((select id from categories where slug = 'fragrance'), 'eau-de-toilette', 'Eau de Toilette', 1)
on conflict (category_id, slug) do nothing;

insert into products (
  slug, name, name_ar, brand, category_id, subcategory_id, description, short_description,
  ingredients, benefits, tags, attributes, price, old_price, currency, discount_percent,
  stock, is_featured, is_new, is_best_seller, is_visible, rating, review_count, images
) values
  ('golden-radiance-serum', 'Golden Radiance Serum', NULL, 'Dr. Karam', (select id from categories where slug = 'skincare'), (select id from subcategories where slug = 'serums' and category_id = (select id from categories where slug = 'skincare')), 'A weightless, fast-absorbing serum formulated with 24k colloidal gold, vitamin C and hyaluronic acid to visibly brighten, firm and hydrate the skin. Dermatologist-developed for daily use, morning and night.', '24k gold-infused brightening serum for a luminous, even complexion.', '{"24K Colloidal Gold","Vitamin C","Hyaluronic Acid","Niacinamide","Squalane"}', '{"Brightens complexion","Reduces fine lines","Deep hydration","Evens skin tone"}', '{"bestseller","brightening"}', '{"concern": ["Brightening", "Hydration"]}'::jsonb, 2450, 2950, 'EGP', NULL, 20, true, true, false, true, 4.8, 214, '[{"url": "https://picsum.photos/seed/serum1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/serum1b/900/1100", "path": null, "position": 1}, {"url": "https://picsum.photos/seed/serum1c/900/1100", "path": null, "position": 2}]'::jsonb),
  ('velvet-rose-night-cream', 'Velvet Rose Night Cream', NULL, 'Velvet Atelier', (select id from categories where slug = 'skincare'), (select id from subcategories where slug = 'moisturizers' and category_id = (select id from categories where slug = 'skincare')), 'Sink into overnight recovery with this luxuriously rich cream, blending Damascus rose extract, ceramides and peptides to restore skin barrier and reduce the appearance of fine lines by morning.', 'Rich, restorative overnight cream with Damascus rose and peptides.', '{"Damascus Rose Extract","Ceramides","Peptide Complex","Shea Butter"}', '{"Deep overnight repair","Softens fine lines","Restores skin barrier"}', '{"night-care"}', '{"concern": ["Anti-Aging", "Hydration"]}'::jsonb, 1890, NULL, 'EGP', NULL, 20, true, false, false, true, 4.6, 132, '[{"url": "https://picsum.photos/seed/cream1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/cream1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('silk-matte-foundation', 'Silk Matte Foundation', NULL, 'Maison Élan', (select id from categories where slug = 'makeup'), (select id from subcategories where slug = 'foundation' and category_id = (select id from categories where slug = 'makeup')), 'A featherlight, buildable foundation that blurs imperfections and controls shine for a natural matte finish that lasts up to 24 hours without settling into fine lines.', 'Full-coverage, second-skin matte foundation, 24h wear.', '{"Silica Microspheres","Vitamin E","SPF 15"}', '{"Full coverage","24h wear","Oil control"}', '{"bestseller"}', '{}'::jsonb, 1350, NULL, 'EGP', NULL, 20, true, true, false, true, 4.7, 301, '[{"url": "https://picsum.photos/seed/found1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/found1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('noir-oud-eau-de-parfum', 'Noir Oud Eau de Parfum', NULL, 'Noir Botanics', (select id from categories where slug = 'fragrance'), (select id from subcategories where slug = 'eau-de-parfum' and category_id = (select id from categories where slug = 'fragrance')), 'An intoxicating oriental composition opening with saffron and rose, deepening into a smoky oud and amber base. Bottled in hand-finished glass for the connoisseur.', 'A smoky, opulent oud fragrance layered with amber and saffron.', '{"Oud","Amber","Saffron","Rose Absolute"}', '{"12h+ longevity","Rich sillage","Unisex scent"}', '{"luxury"}', '{}'::jsonb, 3600, 4200, 'EGP', 15, 20, false, false, false, true, 4.9, 189, '[{"url": "https://picsum.photos/seed/perfume1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/perfume1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('argan-repair-hair-oil', 'Argan Repair Hair Oil', NULL, 'Lumière', (select id from categories where slug = 'haircare'), (select id from subcategories where slug = 'hair-oils' and category_id = (select id from categories where slug = 'haircare')), 'Cold-pressed Moroccan argan oil blended with vitamin E to repair split ends, tame frizz and restore natural shine, without weighing hair down.', 'Nourishing Moroccan argan oil for strength and shine.', '{"Argan Oil","Vitamin E","Jojoba Oil"}', '{"Repairs split ends","Adds shine","Reduces frizz"}', '{"haircare"}', '{"concern": ["Repair", "Shine"]}'::jsonb, 980, NULL, 'EGP', NULL, 20, false, false, false, true, 4.5, 98, '[{"url": "https://picsum.photos/seed/hairoil1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/hairoil1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('champagne-body-butter', 'Champagne Body Butter', NULL, 'Velvet Atelier', (select id from categories where slug = 'bodycare'), (select id from subcategories where slug = 'body-butter' and category_id = (select id from categories where slug = 'bodycare')), 'An indulgent whipped body butter that melts into skin, leaving a subtly luminous champagne shimmer and 48-hour hydration.', 'Whipped shea body butter with a subtle champagne shimmer.', '{"Shea Butter","Cocoa Butter","Mica Shimmer"}', '{"48h hydration","Subtle shimmer finish","Fast-absorbing"}', '{"body"}', '{}'::jsonb, 1120, NULL, 'EGP', NULL, 20, false, true, false, true, 4.4, 76, '[{"url": "https://picsum.photos/seed/body1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/body1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('pearl-infusion-eye-cream', 'Pearl Infusion Eye Cream', NULL, 'Dr. Karam', (select id from categories where slug = 'skincare'), (select id from subcategories where slug = 'eye-care' and category_id = (select id from categories where slug = 'skincare')), 'A cooling, lightweight eye cream that visibly reduces puffiness and dark circles with pearl extract, caffeine and peptides.', 'De-puffing eye cream with pearl extract and caffeine.', '{"Pearl Extract","Caffeine","Peptides","Cucumber Extract"}', '{"Reduces puffiness","Brightens dark circles","Cooling effect"}', '{"eye-care"}', '{"concern": ["Anti-Aging"]}'::jsonb, 1680, NULL, 'EGP', NULL, 20, true, false, false, true, 4.6, 154, '[{"url": "https://picsum.photos/seed/eye1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/eye1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('velvet-matte-lipstick', 'Velvet Matte Lipstick', NULL, 'Maison Élan', (select id from categories where slug = 'makeup'), (select id from subcategories where slug = 'lips' and category_id = (select id from categories where slug = 'makeup')), 'A creamy-to-matte lipstick that glides on effortlessly and sets to a soft-focus finish that lasts through dinner without drying out lips.', 'Weightless matte lipstick in 12 couture shades.', '{"Shea Butter","Vitamin E","Jojoba Esters"}', '{"12h wear","Non-drying formula","12 shades"}', '{"bestseller"}', '{}'::jsonb, 720, NULL, 'EGP', NULL, 20, true, false, false, true, 4.7, 267, '[{"url": "https://picsum.photos/seed/lip1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/lip1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('jasmine-bloom-eau-de-parfum', 'Jasmine Bloom Eau de Parfum', NULL, 'Lumière', (select id from categories where slug = 'fragrance'), (select id from subcategories where slug = 'eau-de-parfum' and category_id = (select id from categories where slug = 'fragrance')), 'An airy, sunlit floral built around Egyptian jasmine, layered with white musk and a citrus top note for effortless daytime elegance.', 'A fresh floral bouquet of jasmine, white musk and citrus.', '{"Jasmine","White Musk","Bergamot"}', '{"Long-lasting","Fresh floral profile"}', '{"floral"}', '{}'::jsonb, 2900, NULL, 'EGP', NULL, 20, false, true, false, true, 4.5, 88, '[{"url": "https://picsum.photos/seed/perfume2/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/perfume2b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('retinol-renewal-complex', 'Retinol Renewal Complex', NULL, 'Dr. Karam', (select id from categories where slug = 'skincare'), (select id from subcategories where slug = 'serums' and category_id = (select id from categories where slug = 'skincare')), 'A clinically-dosed, encapsulated retinol formula that minimizes irritation while delivering visible improvements in texture, tone and fine lines.', 'Encapsulated retinol for smoother, firmer skin overnight.', '{"Encapsulated Retinol","Bakuchiol","Ceramides"}', '{"Smooths texture","Reduces fine lines","Gentle on skin"}', '{"anti-aging"}', '{"concern": ["Anti-Aging"]}'::jsonb, 2150, 2600, 'EGP', 18, 20, false, false, false, true, 4.8, 176, '[{"url": "https://picsum.photos/seed/retinol1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/retinol1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('silk-brow-sculpting-kit', 'Silk Brow Sculpting Kit', NULL, 'Maison Élan', (select id from categories where slug = 'makeup'), (select id from subcategories where slug = 'brows' and category_id = (select id from categories where slug = 'makeup')), 'A dual-ended brow kit combining a tinted wax and setting powder for effortlessly defined, feather-soft brows that hold all day.', 'Wax-to-powder duo for sculpted, natural-looking brows.', '{"Beeswax","Mineral Pigments"}', '{"All-day hold","Natural finish"}', '{"brows"}', '{}'::jsonb, 890, NULL, 'EGP', NULL, 20, false, false, false, true, 4.3, 54, '[{"url": "https://picsum.photos/seed/brow1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/brow1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('coconut-milk-hair-mask', 'Coconut Milk Hair Mask', NULL, 'Noir Botanics', (select id from categories where slug = 'haircare'), (select id from subcategories where slug = 'mask-and-scrubs' and category_id = (select id from categories where slug = 'haircare')), 'A rich, weekly treatment mask infused with coconut milk and biotin that deeply conditions and rebuilds strength in dry or chemically treated hair.', 'Deep conditioning mask for dry, damaged hair.', '{"Coconut Milk","Biotin","Keratin"}', '{"Deep conditioning","Strengthens hair","Adds softness"}', '{"haircare"}', '{"concern": ["Repair"]}'::jsonb, 760, NULL, 'EGP', NULL, 20, false, true, false, true, 4.4, 61, '[{"url": "https://picsum.photos/seed/hairmask1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/hairmask1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('velvet-milk-cleanser', 'Velvet Milk Cleanser', 'غسول فيلفت الحليب', 'Dr. Karam', (select id from categories where slug = 'skincare'), (select id from subcategories where slug = 'cleansers' and category_id = (select id from categories where slug = 'skincare')), 'A creamy, soothing cleanser that melts away makeup and sunscreen while helping preserve the skin barrier and leave the complexion soft and balanced.', 'Gentle milk cleanser with squalane and oat extract.', '{"Squalane","Oat Extract","Ceramides"}', '{"Gentle cleanse","Barrier-friendly","Soft finish"}', '{"gentle","cleansing"}', '{"concern": ["Hydration"]}'::jsonb, 1280, 1550, 'EGP', NULL, 20, true, false, false, true, 4.7, 143, '[{"url": "https://picsum.photos/seed/cleanser2/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/cleanser2b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('midnight-glow-essence', 'Midnight Glow Essence', 'ماء الليل المشرق', 'Lumière', (select id from categories where slug = 'korean'), (select id from subcategories where slug = 'essence' and category_id = (select id from categories where slug = 'korean')), 'A lightweight essence packed with fermented extracts and niacinamide to boost radiance, improve texture and give the skin a naturally luminous finish.', 'K-beauty essence for luminous, glass-like skin.', '{"Fermented Rice Extract","Niacinamide","Panthenol"}', '{"Boosts glow","Improves texture","Lightweight hydration"}', '{"kbeauty","essence"}', '{"concern": ["Brightening"]}'::jsonb, 1540, NULL, 'EGP', NULL, 20, false, true, false, true, 4.8, 112, '[{"url": "https://picsum.photos/seed/essence1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/essence1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('little-bloom-body-lotion', 'Little Bloom Body Lotion', 'لوشن الجسم ليتل بلوم', 'Velvet Atelier', (select id from categories where slug = 'kids'), (select id from subcategories where slug = 'lotion' and category_id = (select id from categories where slug = 'kids')), 'A soft and comforting lotion with shea butter and calendula to keep children''s skin smooth, moisturized and protected throughout the day.', 'Mild, silky body lotion made for delicate skin.', '{"Shea Butter","Calendula","Aloe Vera"}', '{"Gentle hydration","Soft skin feel","Dermatologist friendly"}', '{"kids","hydration"}', '{}'::jsonb, 890, NULL, 'EGP', NULL, 20, false, false, false, true, 4.5, 67, '[{"url": "https://picsum.photos/seed/kidslotion1/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/kidslotion1b/900/1100", "path": null, "position": 1}]'::jsonb),
  ('cocoa-silk-hair-mask', 'Cocoa Silk Hair Mask', 'قناع الشعر الكاكاو السائل', 'Noir Botanics', (select id from categories where slug = 'haircare'), (select id from subcategories where slug = 'mask-and-scrubs' and category_id = (select id from categories where slug = 'haircare')), 'A rich treatment mask infused with cocoa butter and proteins to soften, detangle and restore strength to dry and over-styled hair.', 'Deeply nourishing mask for silky, resilient hair.', '{"Cocoa Butter","Keratin","Argan Oil"}', '{"Deep conditioning","Reduces breakage","Silky finish"}', '{"haircare","treatment"}', '{"concern": ["Repair"]}'::jsonb, 1120, 1370, 'EGP', 18, 20, false, false, false, true, 4.6, 95, '[{"url": "https://picsum.photos/seed/hairmask2/900/1100", "path": null, "position": 0}, {"url": "https://picsum.photos/seed/hairmask2b/900/1100", "path": null, "position": 1}]'::jsonb)
on conflict (slug) do nothing;
